import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../Component/NavBar";
import Footer from "../Component/Footer";
import ChatWidget from "../Component/ChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bidvest",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/img/logo3.jpg" },
    { rel: "apple-touch-icon", url: "/img/logo3.jpg" },
    { rel: "shortcut icon", url: "/img/logo3.jpg" }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img/logo4.jpg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-hero bg-grid bg-cover bg-center min-h-screen">
          <Navbar /> {/* Include the Navbar component */}
          <ChatWidget/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}